datasets:
  adamson: "E:\\CODE\\trishift\\src\\data\\adamson\\perturb_processed.h5ad"
  dixit: "E:\\CODE\\trishift\\src\\data\\dixit\\perturb_processed.h5ad"
  norman: "E:\\CODE\\trishift\\src\\data\\norman\\perturb_processed.h5ad"
  replogle_k562_essential: "E:\\CODE\\trishift\\src\\data\\replogle_k562_essential\\perturb_processed.h5ad"
  replogle_rpe1_essential: "E:\\CODE\\trishift\\src\\data\\replogle_rpe1_essential\\perturb_processed.h5ad"
embeddings:
  emb_a: "E:\\CODE\\trishift\\src\\data\\Data_GeneEmbd\\ensem_emb_gpt3.5all_new.pickle"
  emb_b: "E:\\CODE\\trishift\\src\\data\\Data_GeneEmbd\\GenePT_gene_embedding_ada_text.pickle"
  emb_c: "E:\\CODE\\trishift\\src\\data\\Data_GeneEmbd\\GPT_3_5_gene_embeddings.pickle"
